#!/usr/bin/env python3
"""Build an ATT&CK Navigator layer JSON file from a simple CSV coverage sheet.

Usage:
    python3 generate_navigator_layer.py coverage.csv layer.json \
        [--name "Enterprise coverage - 2026-Q3"] [--domain enterprise-attack] \
        [--attack-version 16]

CSV columns (header required): technique_id,coverage,comment
    technique_id  e.g. T1059.001
    coverage      one of: none, partial, good (case-insensitive)
    comment       free text, optional

No network access is used or required; this only reshapes local data into the
Navigator layer schema (v4.5) for import at
https://mitre-attack.github.io/attack-navigator/.
"""
import argparse
import csv
import json
import sys

COVERAGE_SCORE = {"none": 0, "partial": 50, "good": 100}

GRADIENT_COLORS = ["#ff6666", "#ffe766", "#66b32e"]

LEGEND_ITEMS = [
    {"label": "None (0)", "color": "#ff6666"},
    {"label": "Partial (50)", "color": "#ffe766"},
    {"label": "Good (100)", "color": "#66b32e"},
]


def load_rows(csv_path):
    rows = []
    with open(csv_path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        required = {"technique_id", "coverage"}
        if not required.issubset(set(h.strip() for h in (reader.fieldnames or []))):
            sys.exit(
                f"error: {csv_path} must have a header row with at least "
                f"'technique_id,coverage' columns (optionally 'comment')"
            )
        for i, row in enumerate(reader, start=2):
            tid = (row.get("technique_id") or "").strip()
            level = (row.get("coverage") or "").strip().lower()
            comment = (row.get("comment") or "").strip()
            if not tid:
                continue
            if level not in COVERAGE_SCORE:
                sys.exit(
                    f"error: {csv_path} line {i}: coverage '{level}' for {tid} "
                    f"must be one of none/partial/good"
                )
            rows.append((tid, level, comment))
    if not rows:
        sys.exit(f"error: {csv_path} produced no technique rows")
    return rows


def build_layer(rows, name, domain, attack_version):
    return {
        "name": name,
        "versions": {
            "attack": str(attack_version),
            "navigator": "4.9.1",
            "layer": "4.5",
        },
        "domain": domain,
        "description": (
            "Detection coverage scored None/Partial/Good from validated "
            "telemetry. Generated by attack-technique-mapping's "
            "generate_navigator_layer.py; re-run after every re-score or "
            "matrix re-baseline rather than hand-editing."
        ),
        "techniques": [
            {
                "techniqueID": tid,
                "score": COVERAGE_SCORE[level],
                "color": "",
                "comment": comment,
                "enabled": True,
            }
            for tid, level, comment in rows
        ],
        "gradient": {
            "colors": GRADIENT_COLORS,
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": LEGEND_ITEMS,
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("csv_path", help="input CSV: technique_id,coverage,comment")
    parser.add_argument("json_path", help="output Navigator layer JSON path")
    parser.add_argument("--name", default="ATT&CK detection coverage", help="layer name shown in Navigator")
    parser.add_argument("--domain", default="enterprise-attack", choices=["enterprise-attack", "mobile-attack", "ics-attack"])
    parser.add_argument("--attack-version", default="16", help="ATT&CK matrix version this layer was scored against")
    args = parser.parse_args()

    rows = load_rows(args.csv_path)
    layer = build_layer(rows, args.name, args.domain, args.attack_version)

    with open(args.json_path, "w", encoding="utf-8") as fh:
        json.dump(layer, fh, indent=2)
        fh.write("\n")

    counts = {"none": 0, "partial": 0, "good": 0}
    for _, level, _ in rows:
        counts[level] += 1
    print(
        f"wrote {args.json_path}: {len(rows)} techniques "
        f"(none={counts['none']}, partial={counts['partial']}, good={counts['good']})"
    )


if __name__ == "__main__":
    main()
